//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPSOS_TestDataGenerator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KPPanelConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KPPanelConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IPSOS_TestDataGenerator.Resources.KPPanelConstants", typeof(KPPanelConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEO_CODE,FIRSTNAME_R,LASTNAME_R,HOME_ADDRESS1,HOME_CITY,HOME_STATE,HOME_ZIP,RESPONDENT_R,GENDER_R,AGE_R,HISP_R,RACE_WHITE,RACE_BLACK,RACE_OTHER,RACE_OTHER_TEXT,INTERNET_HOME,HAVE_EMAIL_R,EMAIL_R,PHONE_TYPE_LANDLINE,PHONE_TYPE_OTHER,PHONE_TYPE_CELL,CPOHH,CONTACT_PHONE,CONTACT_PHONE_TYPE,CONF_CONTACT_PHONE,CONF_CONTACT_PHONE_TYPE,BROADBAND,HH_SIZE_12UNDER,HH_SIZE_13TO17,HH_SIZE_18OVER,FIRSTNAME_2,LASTNAME_2,RESPONDENT_2,HAVE_EMAIL_2,SHARE_EMAIL_2,EMAIL_2,GENDER_2,AGE_2,GUARDIAN_2,CONSENT_2,FIRSTNAME_3,LASTNAM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Column_Names {
            get {
                return ResourceManager.GetString("Column_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gourav,Shreyas, Pratik,Akash.
        /// </summary>
        internal static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,1.
        /// </summary>
        internal static string generate_0_1 {
            get {
                return ResourceManager.GetString("generate_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,1,2.
        /// </summary>
        internal static string generate_0_1_2 {
            get {
                return ResourceManager.GetString("generate_0_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,2.
        /// </summary>
        internal static string generate_1_2 {
            get {
                return ResourceManager.GetString("generate_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string generate_ABS_var {
            get {
                return ResourceManager.GetString("generate_ABS_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Generate_AGE_R_var {
            get {
                return ResourceManager.GetString("Generate_AGE_R_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,2,3.
        /// </summary>
        internal static string Generate_Contact_Phone_type_var {
            get {
                return ResourceManager.GetString("Generate_Contact_Phone_type_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,2.
        /// </summary>
        internal static string Generate_GENDER_R_var {
            get {
                return ResourceManager.GetString("Generate_GENDER_R_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,2.
        /// </summary>
        internal static string Generate_HISP_R_var {
            get {
                return ResourceManager.GetString("Generate_HISP_R_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ghdf86,gctw85,ghae56.
        /// </summary>
        internal static string Generate_NEO_CODE_var {
            get {
                return ResourceManager.GetString("Generate_NEO_CODE_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLINE.
        /// </summary>
        internal static string Generate_RECRUITER_ID_var {
            get {
                return ResourceManager.GetString("Generate_RECRUITER_ID_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2,3.
        /// </summary>
        internal static string Generate_RECRUITMENT_MODE_var {
            get {
                return ResourceManager.GetString("Generate_RECRUITMENT_MODE_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,1.
        /// </summary>
        internal static string Generate_RESPONDENT_R_var {
            get {
                return ResourceManager.GetString("Generate_RESPONDENT_R_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS42W2,ABS42W3,ABS42W4,ABS42W5.
        /// </summary>
        internal static string Generate_Sample_var {
            get {
                return ResourceManager.GetString("Generate_Sample_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,2.
        /// </summary>
        internal static string generate_scriptLanguage_var {
            get {
                return ResourceManager.GetString("generate_scriptLanguage_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powder galli,Chichpokali bunder.
        /// </summary>
        internal static string Generate_SHIP_ADDRESS1_var {
            get {
                return ResourceManager.GetString("Generate_SHIP_ADDRESS1_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narmada,Aura.
        /// </summary>
        internal static string Generate_SHIP_APT_var {
            get {
                return ResourceManager.GetString("Generate_SHIP_APT_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pune,aurangabad.
        /// </summary>
        internal static string Generate_SHIP_CITY_var {
            get {
                return ResourceManager.GetString("Generate_SHIP_CITY_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MI,TX.
        /// </summary>
        internal static string Generate_SHIP_STATE_var {
            get {
                return ResourceManager.GetString("Generate_SHIP_STATE_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 43110,45632.
        /// </summary>
        internal static string Generate_SHIP_ZIP_var {
            get {
                return ResourceManager.GetString("Generate_SHIP_ZIP_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1,-2,-3.
        /// </summary>
        internal static string generate_SIGNUPDATE_var {
            get {
                return ResourceManager.GetString("generate_SIGNUPDATE_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,2,3,4.
        /// </summary>
        internal static string Generate_SPANISH_ATHOME_var {
            get {
                return ResourceManager.GetString("Generate_SPANISH_ATHOME_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,2,4.
        /// </summary>
        internal static string generate_WEBTV_var {
            get {
                return ResourceManager.GetString("generate_WEBTV_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,2.
        /// </summary>
        internal static string Household_Members {
            get {
                return ResourceManager.GetString("Household_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Household_Number {
            get {
                return ResourceManager.GetString("Household_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshpande, Nimbalkar, Patil.
        /// </summary>
        internal static string Last_Name {
            get {
                return ResourceManager.GetString("Last_Name", resourceCulture);
            }
        }
    }
}
