//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPSOS_TestDataGenerator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestRunConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestRunConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IPSOS_TestDataGenerator.Resources.TestRunConstants", typeof(TestRunConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=172.29.182.136;Initial Catalog=KNADMIN;User ID=QAakashpr;Password=Pune3244;.
        /// </summary>
        internal static string DatabaseconnectionString {
            get {
                return ResourceManager.GetString("DatabaseconnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO ABS_SAMPLE (ID_Neo,neo_code) values (@ID_Neo,@neo_code).
        /// </summary>
        internal static string InsertNeoCodeCommand {
            get {
                return ResourceManager.GetString("InsertNeoCodeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\TestNeoCode.xlsx.
        /// </summary>
        internal static string KPPanelexcelPath {
            get {
                return ResourceManager.GetString("KPPanelexcelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\TestData.csv.
        /// </summary>
        internal static string testdata_filepath {
            get {
                return ResourceManager.GetString("testdata_filepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\TestData_tabseparated.txt.
        /// </summary>
        internal static string testdata_filepath_tabseparated {
            get {
                return ResourceManager.GetString("testdata_filepath_tabseparated", resourceCulture);
            }
        }
    }
}
